// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0n7oKTvTXUeGRgo4V1nfSB8d_uHc-AE',
    appId: '1:438355490644:web:0e3d442ae4ab40c9cc3ac1',
    messagingSenderId: '438355490644',
    projectId: 'notice-a1dd4',
    authDomain: 'notice-a1dd4.firebaseapp.com',
    storageBucket: 'notice-a1dd4.firebasestorage.app',
    measurementId: 'G-VL1B9YXYPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8w6Vso1jdFhmKRdLYR-uiWWjAabyuxI',
    appId: '1:438355490644:android:5fec6f87838f34edcc3ac1',
    messagingSenderId: '438355490644',
    projectId: 'notice-a1dd4',
    storageBucket: 'notice-a1dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqSoe3GfbdRhrUCE1_ILta77xQdQpga4',
    appId: '1:438355490644:ios:c6c36472f79abc10cc3ac1',
    messagingSenderId: '438355490644',
    projectId: 'notice-a1dd4',
    storageBucket: 'notice-a1dd4.firebasestorage.app',
    iosBundleId: 'com.example.duyuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqSoe3GfbdRhrUCE1_ILta77xQdQpga4',
    appId: '1:438355490644:ios:c6c36472f79abc10cc3ac1',
    messagingSenderId: '438355490644',
    projectId: 'notice-a1dd4',
    storageBucket: 'notice-a1dd4.firebasestorage.app',
    iosBundleId: 'com.example.duyuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw0n7oKTvTXUeGRgo4V1nfSB8d_uHc-AE',
    appId: '1:438355490644:web:fa87fb4d56b6bac2cc3ac1',
    messagingSenderId: '438355490644',
    projectId: 'notice-a1dd4',
    authDomain: 'notice-a1dd4.firebaseapp.com',
    storageBucket: 'notice-a1dd4.firebasestorage.app',
    measurementId: 'G-FC0J9WS6JR',
  );
}
